In [1]:
!pip install pandas scikit-learn nltk

Requirement already satisfied: pandas in c:\users\dell\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\users\dell\anaconda3\lib\site-packages (1.8.0)
Requirement already satisfied: nltk in c:\users\dell\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: click in c:\users\dell\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\dell\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\dell\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\dell\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [2]:
import pandas as pd
import numpy as np
import re

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [7]:
df = pd.read_csv(r"C:\Users\dell\Downloads\New folder\job_title_des.csv")

print(df.head())
print(df.columns)

   Unnamed: 0             Job Title  \
0           0     Flutter Developer
1           1      Django Developer
2           2      Machine Learning
3           3         iOS Developer
4           4  Full Stack Developer

                                     Job Description
0  We are looking for hire experts flutter develo...
1  PYTHON/DJANGO (Developer/Lead) - Job Code(PDJ ...
2  Data Scientist (Contractor)\n\nBangalore, IN\n...
3  JOB DESCRIPTION:\n\nStrong framework outside o...
4  job responsibility full stack engineer – react...
Index(['Unnamed: 0', 'Job Title', 'Job Description'], dtype='object')

In [8]:
# adjust if needed
df = df.rename(columns={
    'Job Title': 'job_title',
    'Job Description': 'job_description'
})

In [9]:
df['text'] = df['job_title'] + " " + df['job_description']

In [10]:
def preprocess(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    return text

df['clean_text'] = df['text'].apply(preprocess)

In [11]:
vectorizer = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

X = vectorizer.fit_transform(df['clean_text'])

In [12]:
def recommend_jobs(user_input):
    user_input = preprocess(user_input)
    user_vector = vectorizer.transform([user_input])
    
    similarity = cosine_similarity(user_vector, X)
    
    scores = similarity[0]
    
    indices = scores.argsort()[::-1]
    
    results = df.iloc[indices][['job_title']].head(5)
    
    return results

In [13]:
recommend_jobs("python machine learning data science")

             job_title
1760  Machine Learning
1333  Machine Learning
1962  Machine Learning
1193  Machine Learning
1106  Machine Learning

In [14]:
def recommend_jobs(user_input):
    user_input = preprocess(user_input)
    user_vector = vectorizer.transform([user_input])
    
    similarity = cosine_similarity(user_vector, X)
    
    scores = similarity[0]
    
    indices = scores.argsort()[::-1]
    
    results = df.iloc[indices][['job_title']].head(5)
    results['match_score'] = scores[indices][:5]
    
    return results

In [15]:
recommend_jobs("python data analysis")

             job_title  match_score
464   Machine Learning     0.347109
885   Machine Learning     0.317514
206   Django Developer     0.307441
2266  Machine Learning     0.305445
901   Django Developer     0.274585